version: '3'
services:
  php:
    build:
      context: docker/php
    #image: php:8.1-fpm
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: "${PMA_ARBITRARY}"